"""add Watchlist

Revision ID: 90da9672137b
Revises: 321e0536ae79
Create Date: 2024-10-22 06:52:13.379756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90da9672137b'
down_revision: Union[str, None] = '321e0536ae79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_holdings_id', table_name='stock_holdings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stock_holdings_id', 'stock_holdings', ['id'], unique=False)
    # ### end Alembic commands ###
